### ISSUE TITLE
Can't compile with qt 5.5.0

### ISSUE THREAD

**Issue by LinArcX** [DylanVanAssche/Qt-Server-Sent-Events-Demo#2]
Hi. First of all, thank you for this repository.
For some reasons i should stick with **_Qt5.5.0_** (Compiler: **_MSVC 2013_**)

I tried to compile your source code, but it failed due to this error arose in `networkmanager.cpp`:
> error: C2039: 'FollowRedirectsAttribute' : is not a member of 'QNetworkRequest'

If i try to comment line 133 in networkmangaer.cpp:
`request.setAttribute(QNetworkRequest::FollowRedirectsAttribute, true);`

I'll get lots of errrors:
```
	C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
	cl -c -nologo -Zc:wchar_t -FS -O2 -MD -Zc:strictStrings -GR -W3 -w34100 -w34189 -w44996 -EHsc -DUNICODE -DWIN32 -DQT_NO_DEBUG -DQT_CORE_LIB -DNDEBUG -I..\QServerSentEvents -I. -I..\..\..\..\myqt\5.5.0\install\msvc2013\32bit\include -I..\..\..\..\myqt\5.5.0\install\msvc2013\32bit\include\QtCore -Irelease -I..\..\..\..\myqt\5.5.0\install\msvc2013\32bit\mkspecs\win32-msvc2013 -Forelease\ @C:\Users\s.mirzakhani\AppData\Local\Temp\networkmanager.obj.16096.0.jom
networkmanager.cpp
	link /NOLOGO /DYNAMICBASE /NXCOMPAT /INCREMENTAL:NO /SUBSYSTEM:CONSOLE,5.01 "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:release\QServerSentEvents.exe @C:\Users\s.mirzakhani\AppData\Local\Temp\QServerSentEvents.exe.16096.468.jom
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall QNetworkRequest::QNetworkRequest(class QUrl const &)" (__imp_??0QNetworkRequest@@QAE@ABVQUrl@@@Z) referenced in function "private: class QNetworkRequest __thiscall Network::Manager::prepareRequest(class QUrl const &)" (?prepareRequest@Manager@Network@@AAE?AVQNetworkRequest@@ABVQUrl@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall QNetworkRequest::~QNetworkRequest(void)" (__imp_??1QNetworkRequest@@QAE@XZ) referenced in function "public: void __thiscall Network::Manager::getResource(class QUrl const &)" (?getResource@Manager@Network@@QAEXABVQUrl@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall QNetworkRequest::setHeader(enum QNetworkRequest::KnownHeaders,class QVariant const &)" (__imp_?setHeader@QNetworkRequest@@QAEXW4KnownHeaders@1@ABVQVariant@@@Z) referenced in function "private: class QNetworkRequest __thiscall Network::Manager::prepareRequest(class QUrl const &)" (?prepareRequest@Manager@Network@@AAE?AVQNetworkRequest@@ABVQUrl@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall QNetworkRequest::setRawHeader(class QByteArray const &,class QByteArray const &)" (__imp_?setRawHeader@QNetworkRequest@@QAEXABVQByteArray@@0@Z) referenced in function "private: class QNetworkRequest __thiscall Network::Manager::prepareRequest(class QUrl const &)" (?prepareRequest@Manager@Network@@AAE?AVQNetworkRequest@@ABVQUrl@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall QNetworkRequest::setAttribute(enum QNetworkRequest::Attribute,class QVariant const &)" (__imp_?setAttribute@QNetworkRequest@@QAEXW4Attribute@1@ABVQVariant@@@Z) referenced in function "private: class QNetworkRequest __thiscall Network::Manager::prepareRequest(class QUrl const &)" (?prepareRequest@Manager@Network@@AAE?AVQNetworkRequest@@ABVQUrl@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall QNetworkAccessManager::QNetworkAccessManager(class QObject *)" (__imp_??0QNetworkAccessManager@@QAE@PAVQObject@@@Z) referenced in function "private: __thiscall Network::Manager::Manager(class QObject *)" (??0Manager@Network@@AAE@PAVQObject@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall QNetworkAccessManager::~QNetworkAccessManager(void)" (__imp_??1QNetworkAccessManager@@UAE@XZ) referenced in function "public: virtual void * __thiscall QNetworkAccessManager::`scalar deleting destructor'(unsigned int)" (??_GQNetworkAccessManager@@UAEPAXI@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class QNetworkReply * __thiscall QNetworkAccessManager::get(class QNetworkRequest const &)" (__imp_?get@QNetworkAccessManager@@QAEPAVQNetworkReply@@ABVQNetworkRequest@@@Z) referenced in function "public: void __thiscall Network::Manager::getResource(class QUrl const &)" (?getResource@Manager@Network@@QAEXABVQUrl@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall QNetworkAccessManager::setConfiguration(class QNetworkConfiguration const &)" (__imp_?setConfiguration@QNetworkAccessManager@@QAEXABVQNetworkConfiguration@@@Z) referenced in function "private: __thiscall Network::Manager::Manager(class QObject *)" (??0Manager@Network@@AAE@PAVQObject@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall QNetworkConfiguration::~QNetworkConfiguration(void)" (__imp_??1QNetworkConfiguration@@QAE@XZ) referenced in function "private: __thiscall Network::Manager::Manager(class QObject *)" (??0Manager@Network@@AAE@PAVQObject@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall QNetworkConfigurationManager::QNetworkConfigurationManager(class QObject *)" (__imp_??0QNetworkConfigurationManager@@QAE@PAVQObject@@@Z) referenced in function "private: __thiscall Network::Manager::Manager(class QObject *)" (??0Manager@Network@@AAE@PAVQObject@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall QNetworkConfigurationManager::~QNetworkConfigurationManager(void)" (__imp_??1QNetworkConfigurationManager@@UAE@XZ) referenced in function "private: __thiscall Network::Manager::Manager(class QObject *)" (??0Manager@Network@@AAE@PAVQObject@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class QNetworkConfiguration __thiscall QNetworkConfigurationManager::defaultConfiguration(void)const " (__imp_?defaultConfiguration@QNetworkConfigurationManager@@QBE?AVQNetworkConfiguration@@XZ) referenced in function "private: __thiscall Network::Manager::Manager(class QObject *)" (??0Manager@Network@@AAE@PAVQObject@@@Z)
networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: class QUrl __thiscall QNetworkReply::url(void)const " (__imp_?url@QNetworkReply@@QBE?AVQUrl@@XZ) referenced in function "private: void __thiscall Network::Manager::streamFinished(class QNetworkReply *)" (?streamFinished@Manager@Network@@AAEXPAVQNetworkReply@@@Z)
networkmanager.obj : error LNK2001: unresolved external symbol "protected: virtual class QNetworkReply * __thiscall QNetworkAccessManager::createRequest(enum QNetworkAccessManager::Operation,class QNetworkRequest const &,class QIODevice *)" (?createRequest@QNetworkAccessManager@@MAEPAVQNetworkReply@@W4Operation@1@ABVQNetworkRequest@@PAVQIODevice@@@Z)
networkmanager.obj : error LNK2001: unresolved external symbol "public: virtual struct QMetaObject const * __thiscall QNetworkAccessManager::metaObject(void)const " (?metaObject@QNetworkAccessManager@@UBEPBUQMetaObject@@XZ)
networkmanager.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall QNetworkAccessManager::qt_metacall(enum QMetaObject::Call,int,void * *)" (?qt_metacall@QNetworkAccessManager@@UAEHW4Call@QMetaObject@@HPAPAX@Z)
networkmanager.obj : error LNK2001: unresolved external symbol "public: virtual void * __thiscall QNetworkAccessManager::qt_metacast(char const *)" (?qt_metacast@QNetworkAccessManager@@UAEPAXPBD@Z)
moc_networkmanager.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static struct QMetaObject const QNetworkReply::staticMetaObject" (__imp_?staticMetaObject@QNetworkReply@@2UQMetaObject@@B) referenced in function "int __cdecl qRegisterNormalizedMetaType<class QNetworkReply *>(class QByteArray const &,class QNetworkReply * *,enum QtPrivate::MetaTypeDefinedHelper<class QNetworkReply *,1>::DefinedType)" (??$qRegisterNormalizedMetaType@PAVQNetworkReply@@@@YAHABVQByteArray@@PAPAVQNetworkReply@@W4DefinedType@?$MetaTypeDefinedHelper@PAVQNetworkReply@@$00@QtPrivate@@@Z)
release\QServerSentEvents.exe : fatal error LNK1120: 19 unresolved externals
```

Edit: Also seems there is no `QSslError` in Qt 5.5.0. But i just want to have a compiled version of your repo.(It doesn't matter if it support SSL or not)

**Comment by DylanVanAssche** [comment]
> error: C2039: 'FollowRedirectsAttribute' : is not a member of 'QNetworkRequest'

According to the [documentation](https://doc.qt.io/qt-5/qnetworkrequest.html), this should not be a problem.
- Are the Qt Network libraries linked?
- `MSVC` is Microsoft's C++ compiler, I suggest you try another one? I only compile my projects on Linux with GCC.
- `QSslError` is also part of Qt's Network libraries as mentioned in the [documentation](https://doc.qt.io/Qt-5/qsslerror.html)

I really suspect that your compiler fails to find these libraries properly...

**Comment by LinArcX** [comment]
TBH, I compiled whole qt on my machine (including qnetwork module)

The interesting thing is that almost all classes of this modules works and links perfectly.
